"""Pydantic models and request shapes for every January AI schema.

Model names are the OpenAPI schema names with the ``Dto`` suffix removed, so a name read in the
API reference is the name imported here. Types ending in ``Param`` are ``TypedDict`` shapes for
values passed *into* SDK methods; everything else is a parsed response or request body.
"""

from __future__ import annotations

from ._base import JanuaryModel
from .auth import ClientTokenResponse, CreateClientToken
from .credits import CreditsResponse
from .food_logs import (
    CreateFoodLog,
    DeleteFoodLogResponse,
    FoodLog,
    FoodLogListResponse,
    LoggedFood,
    ServingDetails,
    UpdateFoodLog,
)
from .food_scans import (
    CorrectScan,
    Detection,
    DetectionFood,
    DetectionServing,
    ScanPhoto,
    ScanResult,
    ScanText,
)
from .foods import (
    AlternativeFood,
    Food,
    FoodAlternative,
    FoodAlternativesRequest,
    FoodAlternativesResponse,
    FoodSearchResponse,
    FoodSelection,
    FoodSelectionParam,
    FoodServing,
    FoodSuggestion,
    FoodSuggestionsResponse,
    ServingSelection,
    ServingSelectionParam,
    ServingSummary,
)
from .glucose import (
    CgmReading,
    CgmReadingParam,
    ConsumedFoodEntry,
    ConsumedFoodEntryParam,
    GlucoseChart,
    GlucosePredict,
    GlucosePredictionPoint,
    GlucosePredictionResponse,
    GlucoseUserProfile,
    GlucoseUserProfileParam,
    Height,
    HeightParam,
    Weight,
    WeightParam,
)
from .restaurants import (
    MenuItem,
    MenuSearchResponse,
    RestaurantResult,
    RestaurantSearchResponse,
)
from .shared import (
    ActivityLevel,
    ApiError,
    AutocompleteCategory,
    DietPreference,
    DietRestriction,
    FoodCategory,
    HealthCondition,
    HeightUnit,
    MacroNutrients,
    NutrientAmount,
    Nutrients,
    Scope,
    Sex,
    WeightUnit,
)

__all__ = [
    "ActivityLevel",
    "AlternativeFood",
    "ApiError",
    "AutocompleteCategory",
    "CgmReading",
    "CgmReadingParam",
    "ClientTokenResponse",
    "ConsumedFoodEntry",
    "ConsumedFoodEntryParam",
    "CorrectScan",
    "CreateClientToken",
    "CreateFoodLog",
    "CreditsResponse",
    "DeleteFoodLogResponse",
    "Detection",
    "DetectionFood",
    "DetectionServing",
    "DietPreference",
    "DietRestriction",
    "Food",
    "FoodAlternative",
    "FoodAlternativesRequest",
    "FoodAlternativesResponse",
    "FoodCategory",
    "FoodLog",
    "FoodLogListResponse",
    "FoodSearchResponse",
    "FoodSelection",
    "FoodSelectionParam",
    "FoodServing",
    "FoodSuggestion",
    "FoodSuggestionsResponse",
    "GlucoseChart",
    "GlucosePredict",
    "GlucosePredictionPoint",
    "GlucosePredictionResponse",
    "GlucoseUserProfile",
    "GlucoseUserProfileParam",
    "HealthCondition",
    "Height",
    "HeightParam",
    "HeightUnit",
    "JanuaryModel",
    "LoggedFood",
    "MacroNutrients",
    "MenuItem",
    "MenuSearchResponse",
    "NutrientAmount",
    "Nutrients",
    "RestaurantResult",
    "RestaurantSearchResponse",
    "ScanPhoto",
    "ScanResult",
    "ScanText",
    "Scope",
    "ServingDetails",
    "ServingSelection",
    "ServingSelectionParam",
    "ServingSummary",
    "Sex",
    "UpdateFoodLog",
    "Weight",
    "WeightParam",
    "WeightUnit",
]
